clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build_step:
    image: plugins/docker
    username: ijiankang@ihealthlabs.com.cn
    password: iHealthStrategy2018
    registry: harbor.ihealthcn.com
    repo: harbor.ihealthcn.com/tonytest/nimei
    mirror: 'https://t8ngg3ge.mirror.aliyuncs.com'
    tag:
      - '${DRONE_BUILD_NUMBER}'
      - latest
    dockerfile: Dockerfile
    when:
      branch: master
      event: push

  jenkins:
    image: appleboy/drone-jenkins
    url: http://172.31.48.2:8080
    user: guanjingtao
    token: b0a83f6a85d9462244d102b372eef7a2
  #  job: BulletBloodPressureSeries/APPAutomation/BloodPressureMonkeyTest
    when:
     status: [ success ]
