clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build_step:
    image: plugins/docker:17.05
    username: admin
    password: Harbor12345
    registry: 120.92.208.210:8099
    repo: 120.92.208.210:8099/library/testTony
    #mirror: 'http://hub-mirror.c.163.com'
    tag:
      - '${DRONE_BUILD_NUMBER}'
      - latest
    dockerfile: Dockerfile
    when:
      branch: master
      event: push
                
