clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build_step:
    image: plugins/docker
    username: admin
    password: Harbor12345
    registry: 120.92.208.210:8099
    repo: 120.92.208.210:8099/tony/library
    mirror: 'https://t8ngg3ge.mirror.aliyuncs.com'
    tag:
      - '${DRONE_BUILD_NUMBER}'
      - latest
    dockerfile: Dockerfile
    when:
      branch: master
      event: push
                
