clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build_step:
    image: plugins/docker
    username: 18211017703@163.com
    password: 51Testing
    registry: http://localhost:8099
    repo: localhost:8099/library/testTony
    mirror: 'http://hub-mirror.c.163.com'
    tag:
      - '${DRONE_BUILD_NUMBER}'
      - latest
    dockerfile: Dockerfile
    when:
      branch: master
      event: push
                
